export const CONNECT_WALLET = "CONNECT_WALLET";
export const DISCONNECT_WALLET = "DISCONNECT_WALLET";
export const TEZOS_INSTANCE = "TEZOS_INSTANCE";
export const CONNECT_WALLET_ERROR = "CONNECT_WALLET_ERROR";
export const SET_VALUE = "SET_VALUE";
export const LOADING = "LOADING";
export const NOT_LOADING = "NOT_LOADING";